services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: finance_assist
      MYSQL_USER: finance_user
      MYSQL_PASSWORD: finance_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - chroma_data:/app/chroma_db
    environment:
      - DJANGO_SETTINGS_MODULE=finance_assist.settings
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL_NAME=${OPENAI_MODEL_NAME:-gpt-4o-mini}
      - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL:-text-embedding-3-small}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.1}
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS:-4096}
      - UNSTRUCTURED_API_KEY=${UNSTRUCTURED_API_KEY}
      - LLAMAPARSE_API_KEY=${LLAMAPARSE_API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=False
      - ALLOWED_HOSTS=*
      - DATABASE_URL=mysql://finance_user:finance_password@db:3306/finance_assist
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  mysql_data:
  chroma_data:
