services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: finance_assist
      MYSQL_USER: finance_user
      MYSQL_PASSWORD: finance_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: finance_user
      PMA_PASSWORD: finance_password
    depends_on:
      - db

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - chroma_data:/app/chroma_db
    environment:
      - DJANGO_SETTINGS_MODULE=finance_assist.settings
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_MODEL_NAME=${OPENAI_MODEL_NAME:-gpt-4o-mini}
      - OPENAI_EMBEDDING_MODEL=${OPENAI_EMBEDDING_MODEL:-text-embedding-3-small}
      - OPENAI_TEMPERATURE=${OPENAI_TEMPERATURE:-0.1}
      - OPENAI_MAX_TOKENS=${OPENAI_MAX_TOKENS:-4096}
      - SECRET_KEY=${SECRET_KEY:-django-insecure-local-development-key}
      - DEBUG=${DEBUG:-True}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-localhost,127.0.0.1}
      - DATABASE_URL=mysql://finance_user:finance_password@db:3306/finance_assist
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mysql_data:
  chroma_data:

