# Generated by Django 5.0.2 on 2025-10-01 15:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeepAgentSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('user_query', models.TextField()),
                ('agent_response', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('sources_used', models.JSONField(default=list)),
                ('processing_time', models.FloatField(default=0.0)),
                ('agent_type', models.CharField(default='deep_agent', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Deep Agent Session',
                'verbose_name_plural': 'Deep Agent Sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('summary', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('faqs', models.JSONField(default=list)),
                ('source_path', models.CharField(max_length=1000)),
                ('chunk_count', models.IntegerField(default=0)),
                ('processing_timestamp', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document Metadata',
                'verbose_name_plural': 'Document Metadata',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrichedChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('summary', models.TextField()),
                ('keywords', models.JSONField(default=list)),
                ('faq', models.TextField(blank=True, null=True)),
                ('chunk_id', models.CharField(max_length=100, unique=True)),
                ('document_id', models.CharField(max_length=100)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_metadata', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='chat.documentmetadata')),
            ],
            options={
                'verbose_name': 'Enriched Chunk',
                'verbose_name_plural': 'Enriched Chunks',
                'ordering': ['document_metadata', 'chunk_id'],
            },
        ),
    ]
