# Generated by Django 5.0.2 on 2025-10-15 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_deepagentsession_documentmetadata_enrichedchunk'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='deepagentsession',
            options={'ordering': ['-updated_at'], 'verbose_name': 'Deep Agent Session', 'verbose_name_plural': 'Deep Agent Sessions'},
        ),
        migrations.RemoveField(
            model_name='deepagentsession',
            name='agent_response',
        ),
        migrations.RemoveField(
            model_name='deepagentsession',
            name='agent_type',
        ),
        migrations.RemoveField(
            model_name='deepagentsession',
            name='confidence_score',
        ),
        migrations.RemoveField(
            model_name='deepagentsession',
            name='processing_time',
        ),
        migrations.RemoveField(
            model_name='deepagentsession',
            name='sources_used',
        ),
        migrations.RemoveField(
            model_name='deepagentsession',
            name='user_query',
        ),
        migrations.AddField(
            model_name='deepagentsession',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='deepagentsession',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('retriever_type', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(blank=True, max_length=50, null=True)),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('sources', models.JSONField(blank=True, default=list)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('search_stats', models.JSONField(blank=True, default=dict)),
                ('rag_details', models.JSONField(blank=True, default=dict)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.conversation')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['created_at'],
            },
        ),
    ]
